### ISSUE TITLE
Remove CXF support

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#246]
## Description
After the discussion on the [krazo-dev mailing list](https://www.eclipse.org/lists/krazo-dev/msg00143.html) regarding this topic, we decided to remove the CXF support from Krazo Core and the whole Krazo CXF module.
A short list of reasons for the decission is:
- TomEE is the last mainstream application server using CXF as JAX-RS implementation, as OpenLiberty is going to use RESTEasy in the future
- CXF takes the most effort for maintenance and integration, whereas it is used only for one server which we assume as a "minor player"
- We need workarounds for CXF in the Krazo Core Module because of missing SPIs. From an architectural point of view, this is nothing we really want to have in the long term

## TODOs
- [x] Drop `krazo-cxf` module
- [x] Remove workarounds from `krazo-core`
- [x] Remove CXF related code from integration tests
- [x] Adapt documentation
- [x] Add some kind of release notes document for easier change tracking 
- [x] Remove Jenkins jobs for CXF / TomEE. Stop Jobs for OpenLiberty as long as it uses CXF
