### ISSUE TITLE
Update Arquillian connector for OpenLiberty and Jakarta EE 9

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#295]
Since a while there are a few more configs to make, to get the OpenLiberty testsuite running again against the latest stable version:

https://github.com/OpenLiberty/liberty-arquillian/blob/main/liberty-remote/JakartaEE9_README.md

## TODOs

- [ ] Update the OL connector dependency to `io.openliberty.arquillian:arquillian-liberty-managed-jakarta:2.0.2`
- [ ] Update template for `server.xml` in the legacy `.travis` directory (and move this file into some other directory)
- [ ] Check if `arquillian.xml` is still correctly configured
- [ ] do the same in `tck` module
