### ISSUE TITLE
Replace `org.eclipse.krazo.defaultViewFileExtension` with API constant

### ISSUE THREAD

**Issue by erdlet** [eclipse-ee4j/krazo#369]
In https://github.com/jakartaee/mvc/issues/38 we standardized the above mentioned constant, so we can replace the Krazo specific one.

##  Tasks

- [ ] The Krazo specific constant is defined in `org.eclipse.krazo.Properties:54` as `DEFAULT_VIEW_FILE_EXTENSION`. It needs to be removed.
- [ ] In `org.eclipse.krazo.KrazoConfig:72` the constant is used inside `getDefaultViewFileExtension()`. Replace it with `jakarta.mvc.engine.ViewEngine#VIEW_EXTENSION`
- [ ] Check if there are any tests covering this issue. If yes: please adapt it. If not: please add one
